DROP TABLE IF EXISTS EMPLOYEE;

CREATE TABLE EMPLOYEE
(
EmployeeId BIGINT AUTO_INCREMENT  PRIMARY KEY NOT NULL,
EmployeeName VARCHAR(50) NOT NULL,
Title VARCHAR(50) NOT NULL,
BusinessUnit VARCHAR(10) NOT NULL,
Place VARCHAR(50) NOT NULL,
SupervisorId INT,
Competencies VARCHAR(50) NOT NULL,
Salary INT NOT NULL
);